### ISSUE TITLE
General Progress toward 1.0.0

### ISSUE THREAD

**Issue by caseif** [caseif/Steel#1]
This issue is a checklist for work that needs to be done to achieve 1.0.0 of the Steel plugin. I'll be updating it as I progress. It's not set in stone, and is subject to change at any given time.

**Current task:** Beta-phase QA testing
**ETA:** Late September/Early October
- [x] Implement automatic arena management
- [x] Handle events which would otherwise screw up rounds
- [x] Handle keeping players physically in the arena
- [x] Persistence implementation
- [x] Finish implementing config options
- [x] Implement rollbacks
- [x] Alpha-phase QA testing
- [x] Implement lobby system
- [x] Audit and feature-freeze Flint 1.0
- [x] Finish writing tutorial (Flint)
- [x] Beta-phase QA testing

**Current overall ETA:** Late September/Early October

**Comment by hfoxy** [comment]
Just a tip, you should probably use a Trello board for the task management, with something like Zapier to create a new issue for each card. You'll be able to manage and view progress on your milestones much easier.

Anyways, good luck with the project, seems pretty interesting!
