### ISSUE TITLE
1.9.4: PlayerJoinEvent

### ISSUE THREAD

**Issue by Emalton** [caseif/Steel#5]
http://pastebin.com/2Yssmk38

Would also be nice if you could support PlugMan. (When a plugin is unloaded, unregister it from Steel.)

**Comment by caseif** [comment]
Hm... I think I broke something imporatant. It's late right now so I'll have to take a look at it tomorrow. Thanks for the report. :)

**Comment by Emalton** [comment]
Awesome! Thanks for being amazing! I love your API!

**Comment by caseif** [comment]
Fixed in 24840a5. Thanks for the kind words, btw!
